#!/usr/bin/env python3
"""
Builds Neko/Resources/deckfonts/ - the typefaces presentation themes ship with.

Each theme font is downloaded from the Google Fonts CSS API, which serves a
static TrueType instance per weight to a non-browser client, and written with:

  deck-fonts.css   @font-face rules the deck pages load (no Google Fonts request)
  deck-fonts.json  the catalog the PowerPoint export reads: for each family and
                   weight, the typeface name PowerPoint knows it by, the slot
                   (regular or bold) and the file to embed

PowerPoint only has regular and bold. A static instance at any other weight is a
family of its own (Google names the 500 instance of Schibsted Grotesk
"Schibsted Grotesk Medium"), so that is the typeface the export writes, with the
file in its regular slot. The typeface is read from the font's own name table
(name ID 1), which is what PowerPoint matches an embedded font by.

    python3 reference/deck-fonts/build-deck-fonts.py

Needs fontTools (pip install fonttools). Every font here is licensed OFL 1.1.
"""
import io, json, os, re, sys, urllib.parse, urllib.request

from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', 'Neko', 'Resources', 'deckfonts')

# family -> weights shipped. The curiosity theme sets Schibsted Grotesk at 400
# and 500 (600 is the wordmark's) and Geist Mono at 400 and 500.
FONTS = {
    'Schibsted Grotesk': [400, 500, 600, 700],
    'Geist Mono': [400, 500, 700],
}
WEIGHT_NAMES = {100: 'Thin', 200: 'ExtraLight', 300: 'Light', 400: 'Regular', 500: 'Medium',
                600: 'SemiBold', 700: 'Bold', 800: 'ExtraBold', 900: 'Black'}


def get(url):
    req = urllib.request.Request(url, headers={'User-Agent': 'curl/8'})
    return urllib.request.urlopen(req, timeout=60).read()


def main():
    os.makedirs(OUT, exist_ok=True)
    catalog, css = {}, ['/* Generated by reference/deck-fonts/build-deck-fonts.py. Fonts: SIL Open Font License 1.1. */']
    for family, weights in FONTS.items():
        for weight in weights:
            query = 'family=' + urllib.parse.quote_plus(family) + f':wght@{weight}'
            sheet = get('https://fonts.googleapis.com/css2?' + query).decode()
            url = re.search(r'src: url\((\S+?\.ttf)\)', sheet)
            if not url:
                sys.exit(f'no TrueType file for {family} {weight}')
            data = get(url.group(1))
            if data[:4] != b'\x00\x01\x00\x00':
                sys.exit(f'{family} {weight} is not TrueType: PowerPoint only embeds TrueType outlines')
            font = TTFont(io.BytesIO(data))
            typeface = font['name'].getDebugName(1)
            subfamily = font['name'].getDebugName(2) or 'Regular'
            if font['OS/2'].fsType & 0x0002:
                sys.exit(f'{family} {weight} forbids embedding (fsType {font["OS/2"].fsType})')
            name = family.replace(' ', '') + '-' + WEIGHT_NAMES[weight] + '.ttf'
            with open(os.path.join(OUT, name), 'wb') as f:
                f.write(data)
            catalog.setdefault(family, {})[str(weight)] = {
                'typeface': typeface,
                'slot': 'bold' if subfamily.lower().startswith('bold') else 'regular',
                'file': name,
            }
            css.append('@font-face{font-family:"%s";font-style:normal;font-weight:%d;font-display:swap;src:url("%s") format("truetype")}'
                       % (family, weight, name))
            print(f'{name:36} {len(data):>7} bytes  typeface "{typeface}" {subfamily}')
    with open(os.path.join(OUT, 'deck-fonts.json'), 'w') as f:
        json.dump(catalog, f, indent=1, sort_keys=True)
        f.write('\n')
    with open(os.path.join(OUT, 'deck-fonts.css'), 'w') as f:
        f.write('\n'.join(css) + '\n')


if __name__ == '__main__':
    main()
