#!/usr/bin/env python3
"""
Builds Neko/Builder/DocumentArt.Wordmark.cs - the Curiosity wordmark as outlines.

The paged-document lockup (the Escape mark and "curiosity") is drawn as an SVG whose
wordmark is a path, so it needs no font on the page and rasterises the same in the
Word export. The wordmark is "cur\u0131os\u0131ty" in Schibsted Grotesk SemiBold with -0.03em
tracking and kerning (HarfBuzz); the two dotless i's get the brand's square dots,
placed as the site's CSS places them (.073em across, .126em down the line box).

    pip install fonttools uharfbuzz
    python3 reference/deck-fonts/build-lockup.py
"""
import os, re
import uharfbuzz as hb
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
FONT = os.path.join(HERE, '..', '..', 'Neko', 'Resources', 'deckfonts', 'SchibstedGrotesk-SemiBold.ttf')
OUT = os.path.join(HERE, '..', '..', 'Neko', 'Builder', 'DocumentArt.Wordmark.cs')
TEXT = 'cur\u0131os\u0131ty'
TRACKING = -0.03

tt = TTFont(FONT)
upm = tt['head'].unitsPerEm
asc, desc = tt['hhea'].ascent / upm, -tt['hhea'].descent / upm
baseline = (1 - (asc + desc)) / 2 + asc          # line-height 1: the baseline's distance from the top

font = hb.Font(hb.Face(hb.Blob.from_file_path(FONT)))
buf = hb.Buffer(); buf.add_str(TEXT); buf.guess_segment_properties()
hb.shape(font, buf, {'kern': True, 'liga': True})
glyphs, order = tt.getGlyphSet(), tt.getGlyphOrder()

x, paths, dots = 0.0, [], []
for i, (info, pos) in enumerate(zip(buf.glyph_infos, buf.glyph_positions)):
    pen = SVGPathPen(glyphs)
    s = 1000 / upm
    glyphs[order[info.codepoint]].draw(TransformPen(pen, (s, 0, 0, -s, (x + pos.x_offset / upm) * 1000, baseline * 1000)))
    if pen.getCommands(): paths.append(pen.getCommands())
    if TEXT[i] == '\u0131': dots.append((x + 0.073, 0.126, 0.122))
    x += pos.x_advance / upm + TRACKING

d = re.sub(r'-?\d+\.\d+', lambda m: ('%.1f' % float(m.group())).rstrip('0').rstrip('.'), ' '.join(paths))
cs = """using System.Globalization;
using System.Text;

namespace Neko.Builder
{
    public static partial class DocumentArt
    {
        // The Curiosity wordmark, "cur\u0131os\u0131ty" in Schibsted Grotesk SemiBold with -0.03em tracking,
        // outlined (units: 1/1000 em, baseline at y = %.1f) so it draws without the font. The two
        // dotless i's get the brand's square dots (WordmarkDots: x, y, size in 1/1000 em).
        // Generated by reference/deck-fonts/build-lockup.py.
        private const string WordmarkPath = "%s";
        private const double WordmarkWidth = %.1f;
        private static readonly double[][] WordmarkDots = { %s };
    }
}
""" % (baseline * 1000, d, x * 1000, ', '.join('new[] { %.1f, %.1f, %.1f }' % (a * 1000, b * 1000, c * 1000) for a, b, c in dots))
open(OUT, 'w', encoding='utf8').write(cs)
print('wrote', os.path.normpath(OUT))
