using System.Text;

namespace Neko.Builder
{
    public partial class HtmlGenerator
    {
        private void RenderWatchModeUi(StringBuilder sb)
        {
            // The editor modal/Monaco chrome is skipped in live-only mode
            // (`neko watch --live`); the live-reload WebSocket below always runs.
            if (_showEditor)
            {
                RenderWatchEditorModal(sb);
            }
            RenderWatchScript(sb);
        }

        private void RenderWatchEditorModal(StringBuilder sb)
        {
            sb.AppendLine("    <div id=\"neko-editor-modal\" class=\"fixed inset-0 z-50 hidden\">");
            sb.AppendLine("        <div class=\"absolute inset-0 bg-black/50 backdrop-blur-sm\"></div>");
            sb.AppendLine("        <div class=\"absolute inset-0 flex items-center justify-center p-4\">");
            sb.AppendLine("            <div class=\"bg-white dark:bg-gray-900 w-full max-w-6xl h-[90vh] rounded-lg shadow-xl flex flex-col border border-gray-200 dark:border-gray-700\">");
            sb.AppendLine("                <div class=\"flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700\">");
            sb.AppendLine("                    <h3 class=\"text-lg font-semibold text-gray-900 dark:text-gray-100 flex items-center\">Edit Content<span class=\"text-xs text-gray-500 dark:text-gray-400 font-normal ml-3 hidden md:inline\">Press <kbd class=\"px-1 py-0.5 rounded border border-gray-300 dark:border-gray-600 bg-gray-100 dark:bg-gray-800 text-gray-500 dark:text-gray-400 font-sans text-[10px] mx-1\">Ctrl</kbd>+<kbd class=\"px-1 py-0.5 rounded border border-gray-300 dark:border-gray-600 bg-gray-100 dark:bg-gray-800 text-gray-500 dark:text-gray-400 font-sans text-[10px] mx-1\">I</kbd> for icons</span></h3>");
            sb.AppendLine("                    <div class=\"flex items-center gap-2\">");
            sb.AppendLine("                        <button onclick=\"nekoCancelEdit()\" class=\"px-3 py-1.5 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-md transition-colors\">Cancel</button>");
            sb.AppendLine("                        <button onclick=\"nekoSaveContent()\" class=\"px-3 py-1.5 text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 rounded-md transition-colors\">Save</button>");
            sb.AppendLine("                    </div>");
            sb.AppendLine("                </div>");
            sb.AppendLine("                <div id=\"neko-editor-container\" class=\"flex-1 overflow-hidden\"></div>");
            sb.AppendLine("            </div>");
            sb.AppendLine("        </div>");
            sb.AppendLine("    </div>");
        }

        private void RenderWatchScript(StringBuilder sb)
        {
            sb.AppendLine("    <script>");
            sb.AppendLine("        // WebSocket for Live Reload");
            sb.AppendLine("        const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';");
            sb.AppendLine("        const wsUrl = `${protocol}//${window.location.host}/neko-live`;");
            sb.AppendLine("        let ws;");
            sb.AppendLine("");
            sb.AppendLine("        function connectWs() {");
            sb.AppendLine("            ws = new WebSocket(wsUrl);");
            sb.AppendLine("            ws.onmessage = (event) => {");
            sb.AppendLine("                if (event.data === 'reload') {");
            sb.AppendLine("                    window.location.reload();");
            sb.AppendLine("                }");
            sb.AppendLine("            };");
            sb.AppendLine("            ws.onclose = () => {");
            sb.AppendLine("                setTimeout(connectWs, 1000);");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("        connectWs();");
            sb.AppendLine("");

            // Everything below is the in-browser editor (Monaco modal, content
            // save, sidebar drag-reorder). In live-only mode (`neko watch --live`)
            // we keep the live-reload above but emit none of the editing chrome,
            // matching what a release build ships.
            if (!_showEditor)
            {
                sb.AppendLine("    </script>");
                return;
            }

            sb.AppendLine("        // Monaco Editor");
            sb.AppendLine("        let editor;");
            sb.AppendLine("        const modal = document.getElementById('neko-editor-modal');");
            sb.AppendLine("        const container = document.getElementById('neko-editor-container');");
            sb.AppendLine("");


            sb.AppendLine("        function loadMonaco(callback) {");
            sb.AppendLine("            if (window.nekoMonacoLoaded) {");
            sb.AppendLine("                callback();");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine("            const script = document.createElement('script');");
            sb.AppendLine("            script.src = 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.44.0/min/vs/loader.min.js';");
            sb.AppendLine("            script.onload = () => {");
            sb.AppendLine("                require.config({ paths: { 'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.44.0/min/vs' }});");
            sb.AppendLine("                require(['vs/editor/editor.main'], function() {");
            sb.AppendLine("                    var currentPath = window.location.pathname;");
            sb.AppendLine("                    var inRoot = currentPath === '/' || currentPath.indexOf('/', 1) === -1;");
            sb.AppendLine("                    var templatesUrl = inRoot ? '/assets/templates.json' : window.nekoRootPath + 'assets/templates.json';");
            sb.AppendLine("                    if (!window.nekoRootPath && !inRoot) {");
            sb.AppendLine("                        var depth = currentPath.split('/').length - 2;");
            sb.AppendLine("                        var prefix = depth > 0 ? '../'.repeat(depth) : './';");
            sb.AppendLine("                        templatesUrl = prefix + 'assets/templates.json';");
            sb.AppendLine("                    }");
            sb.AppendLine("                    fetch(templatesUrl).then(res => res.json()).then(templates => {");
            sb.AppendLine("                        monaco.languages.registerCompletionItemProvider('markdown', {");
            sb.AppendLine("                            provideCompletionItems: function(model, position) {");
            sb.AppendLine("                                var word = model.getWordUntilPosition(position);");
            sb.AppendLine("                                var lineContent = model.getLineContent(position.lineNumber);");
            sb.AppendLine("                                var match = lineContent.substring(0, position.column - 1).match(/neko-\\w*$/);");
            sb.AppendLine("                                var startCol = match ? (position.column - match[0].length) : word.startColumn;");
            sb.AppendLine("                                var range = {");
            sb.AppendLine("                                    startLineNumber: position.lineNumber,");
            sb.AppendLine("                                    endLineNumber: position.lineNumber,");
            sb.AppendLine("                                    startColumn: startCol,");
            sb.AppendLine("                                    endColumn: word.endColumn");
            sb.AppendLine("                                };");
            sb.AppendLine("                                var suggestions = [];");
            sb.AppendLine("                                for (const [key, value] of Object.entries(templates)) {");
            sb.AppendLine("                                    suggestions.push({");
            sb.AppendLine("                                        label: key,");
            sb.AppendLine("                                        kind: monaco.languages.CompletionItemKind.Snippet,");
            sb.AppendLine("                                        insertText: value,");
            sb.AppendLine("                                        insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,");
            sb.AppendLine("                                        documentation: 'Neko template: ' + key,");
            sb.AppendLine("                                        range: range");
            sb.AppendLine("                                    });");
            sb.AppendLine("                                }");
            sb.AppendLine("                                return { suggestions: suggestions };");
            sb.AppendLine("                            }");
            sb.AppendLine("                        });");
            sb.AppendLine("                        window.nekoMonacoLoaded = true;");
            sb.AppendLine("                        callback();");
            sb.AppendLine("                    }).catch(err => {");
            sb.AppendLine("                        console.error('Failed to load templates', err);");
            sb.AppendLine("                        window.nekoMonacoLoaded = true;");
            sb.AppendLine("                        callback();");
            sb.AppendLine("                    });");
            sb.AppendLine("                });");
            sb.AppendLine("            };");
            sb.AppendLine("            document.body.appendChild(script);");
            sb.AppendLine("        }");
            sb.AppendLine("");

            sb.AppendLine("        function nekoOpenEditorPath(path, event) {");
sb.AppendLine("            if (event) {");
sb.AppendLine("                event.preventDefault();");
sb.AppendLine("                event.stopPropagation();");
sb.AppendLine("            }");
sb.AppendLine("            fetch('/api/neko/content?path=' + encodeURIComponent(path))");
sb.AppendLine("                .then(res => {");
sb.AppendLine("                    if (!res.ok) throw new Error('Not found');");
sb.AppendLine("                    return res.text();");
sb.AppendLine("                })");
sb.AppendLine("                .then(markdown => {");
sb.AppendLine("                    modal.classList.remove('hidden');");
sb.AppendLine("                    loadMonaco(() => {");
sb.AppendLine("                        require.config({ paths: { 'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.44.0/min/vs' }});");
sb.AppendLine("                        require(['vs/editor/editor.main'], function() {");
sb.AppendLine("                            if (editor) {");
sb.AppendLine("                                monaco.editor.setModelLanguage(editor.getModel(), 'yaml');");
sb.AppendLine("                                editor.setValue(markdown);");
sb.AppendLine("                            } else {");
sb.AppendLine("                                editor = monaco.editor.create(container, {");
sb.AppendLine("                                    value: markdown,");
sb.AppendLine("                                    language: 'yaml',");
sb.AppendLine("                                    theme: document.documentElement.classList.contains('dark') ? 'vs-dark' : 'vs',");
sb.AppendLine("                                    automaticLayout: true,");
sb.AppendLine("                                    minimap: { enabled: false },");
sb.AppendLine("                                    wordWrap: 'on',");
sb.AppendLine("                                    pasteAs: { enabled: false, },");
sb.AppendLine("                                    fontSize: 14");
sb.AppendLine("                                });");
sb.AppendLine("                            }");
sb.AppendLine("                            window.nekoCurrentEditPath = path;");
sb.AppendLine("                        });");
sb.AppendLine("                    });");
sb.AppendLine("                })");
sb.AppendLine("                .catch(err => {");
sb.AppendLine("                    modal.classList.remove('hidden');");
sb.AppendLine("                    loadMonaco(() => {");
sb.AppendLine("                        require.config({ paths: { 'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.44.0/min/vs' }});");
sb.AppendLine("                        require(['vs/editor/editor.main'], function() {");
sb.AppendLine("                            const defaultYaml = \"# Folder Configuration\\n# Valid options:\\n# order: 0           # Sorting order (lower numbers appear first)\\n# label: 'My Title'  # The display title of the folder in the sidebar\\n# icon: 'folder'     # The Flaticon UIcon name (e.g., folder, star, layout-grid)\\n# expanded: false    # Whether the folder is expanded by default in the sidebar\\n# visibility: public # public | hidden (out of nav & search) | protected | private\\n\\norder: 0\\nlabel: ''\\nicon: ''\\nexpanded: false\\n\";");
sb.AppendLine("                            if (editor) {");
sb.AppendLine("                                monaco.editor.setModelLanguage(editor.getModel(), 'yaml');");
sb.AppendLine("                                editor.setValue(defaultYaml);");
sb.AppendLine("                            } else {");
sb.AppendLine("                                editor = monaco.editor.create(container, {");
sb.AppendLine("                                    value: defaultYaml,");
sb.AppendLine("                                    language: 'yaml',");
sb.AppendLine("                                    theme: document.documentElement.classList.contains('dark') ? 'vs-dark' : 'vs',");
sb.AppendLine("                                    automaticLayout: true,");
sb.AppendLine("                                    minimap: { enabled: false },");
sb.AppendLine("                                    wordWrap: 'on',");
sb.AppendLine("                                    pasteAs: { enabled: false, },");
sb.AppendLine("                                    fontSize: 14");
sb.AppendLine("                                });");
sb.AppendLine("                            }");
sb.AppendLine("                            window.nekoCurrentEditPath = path;");
sb.AppendLine("                        });");
sb.AppendLine("                    });");
sb.AppendLine("                });");
sb.AppendLine("        }");
sb.AppendLine("");
sb.AppendLine("        function nekoOpenEditor() {");
sb.AppendLine("            window.nekoCurrentEditPath = window.location.pathname;");
sb.AppendLine("            window.nekoCurrentEditPath = window.location.pathname;");
            sb.AppendLine("            const path = window.location.pathname;");
            sb.AppendLine("            fetch('/api/neko/content?path=' + encodeURIComponent(path))");
            sb.AppendLine("                .then(res => res.text())");
            sb.AppendLine("                .then(markdown => {");
            sb.AppendLine("                    modal.classList.remove('hidden');");
            sb.AppendLine("                    loadMonaco(() => {");
            sb.AppendLine("                        require.config({ paths: { 'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.44.0/min/vs' }});");
            sb.AppendLine("                        require(['vs/editor/editor.main'], function() {");
            sb.AppendLine("                            if (editor) {");
            sb.AppendLine("                                editor.setValue(markdown);");
            sb.AppendLine("                            } else {");
            sb.AppendLine("                                editor = monaco.editor.create(container, {");
            sb.AppendLine("                                    value: markdown,");
            sb.AppendLine("                                    language: 'markdown',");
            sb.AppendLine("                                    theme: document.documentElement.classList.contains('dark') ? 'vs-dark' : 'vs',");
            sb.AppendLine("                                    automaticLayout: true,");
            sb.AppendLine("                                    minimap: { enabled: false },");
            sb.AppendLine("                                    wordWrap: 'on',");
            sb.AppendLine("                                    pasteAs: { enabled: false, },");
            sb.AppendLine("                                    fontSize: 14");
            sb.AppendLine("                                });");
            sb.AppendLine("");



            sb.AppendLine("                                // Image Paste Handler");
            sb.AppendLine("                    editor.getContainerDomNode().addEventListener('paste', (event) => {");
            sb.AppendLine("                                    if (!editor || !editor.hasTextFocus()) return;");
            sb.AppendLine("                                    const items = (event.clipboardData || event.originalEvent.clipboardData).items;");
            sb.AppendLine("                                    for (const item of items) {");
            sb.AppendLine("                                        if (item.kind === 'file' && item.type.startsWith('image/')) {");
            sb.AppendLine("                                            event.preventDefault();");
            sb.AppendLine("                                            const file = item.getAsFile();");
            sb.AppendLine("                                            const path = window.location.pathname;");
            sb.AppendLine("                                            const formData = new FormData();");
            sb.AppendLine("                                            formData.append('file', file);");
            sb.AppendLine("                                            formData.append('path', path);");
            sb.AppendLine("                                            fetch('/api/neko/upload-image', {");
            sb.AppendLine("                                                method: 'POST',");
            sb.AppendLine("                                                body: formData");
            sb.AppendLine("                                            })");
            sb.AppendLine("                                            .then(res => {");
            sb.AppendLine("                                                if (!res.ok) throw new Error('Upload failed');");
            sb.AppendLine("                                                return res.json();");
            sb.AppendLine("                                            })");
            sb.AppendLine("                                            .then(data => {");
            sb.AppendLine("                                                const imageUrl = data.url;");
            sb.AppendLine("                                                const markdownImage = `![Image](${imageUrl})`;");
            sb.AppendLine("                                                const position = editor.getPosition();");
            sb.AppendLine("                                                editor.executeEdits('paste-image', [{");
            sb.AppendLine("                                                    range: new monaco.Range(position.lineNumber, position.column, position.lineNumber, position.column),");
            sb.AppendLine("                                                    text: markdownImage,");
            sb.AppendLine("                                                    forceMoveMarkers: true");
            sb.AppendLine("                                                }]);");
            sb.AppendLine("                                            })");
            sb.AppendLine("                                            .catch(err => {");
            sb.AppendLine("                                                console.error('Image upload failed', err);");
            sb.AppendLine("                                                alert('Failed to upload image: ' + err.message);");
            sb.AppendLine("                                            });");
            sb.AppendLine("                                        }");
            sb.AppendLine("                                    }");
            sb.AppendLine("                                });");

            //Disabled the following code as image data is not available as part of clipboardEvent for now (see https://github.com/microsoft/monaco-editor/issues/4030)
            //sb.AppendLine("                                editor.onDidPaste((e) => {");
            //sb.AppendLine("                                    if (!e.clipboardEvent) return;");
            //sb.AppendLine("                                    const event = e.clipboardEvent;");
            //sb.AppendLine("                                    const items = (event.clipboardData || event.originalEvent?.clipboardData)?.items;");
            //sb.AppendLine("                                    if (!items) return;");
            //sb.AppendLine("                                    for (const item of items) {");
            //sb.AppendLine("                                        if (item.kind === 'file' && item.type.startsWith('image/')) {");
            //sb.AppendLine("                                            event.preventDefault();");
            //sb.AppendLine("                                            const file = item.getAsFile();");
            //sb.AppendLine("                                            const path = window.location.pathname;");
            //sb.AppendLine("                                            const formData = new FormData();");
            //sb.AppendLine("                                            formData.append('file', file);");
            //sb.AppendLine("                                            formData.append('path', path);");
            //sb.AppendLine("                                            fetch('/api/neko/upload-image', {");
            //sb.AppendLine("                                                method: 'POST',");
            //sb.AppendLine("                                                body: formData");
            //sb.AppendLine("                                            })");
            //sb.AppendLine("                                            .then(res => {");
            //sb.AppendLine("                                                if (!res.ok) throw new Error('Upload failed');");
            //sb.AppendLine("                                                return res.json();");
            //sb.AppendLine("                                            })");
            //sb.AppendLine("                                            .then(data => {");
            //sb.AppendLine("                                                const imageUrl = data.url;");
            //sb.AppendLine("                                                const markdownImage = `![Image](${imageUrl})`;");
            //sb.AppendLine("                                                const position = editor.getPosition();");
            //sb.AppendLine("                                                editor.executeEdits('paste-image', [{");
            //sb.AppendLine("                                                    range: new monaco.Range(position.lineNumber, position.column, position.lineNumber, position.column),");
            //sb.AppendLine("                                                    text: markdownImage,");
            //sb.AppendLine("                                                    forceMoveMarkers: true");
            //sb.AppendLine("                                                }]);");
            //sb.AppendLine("                                            })");
            //sb.AppendLine("                                            .catch(err => {");
            //sb.AppendLine("                                                console.error('Image upload failed', err);");
            //sb.AppendLine("                                                alert('Failed to upload image: ' + err.message);");
            //sb.AppendLine("                                            });");
            //sb.AppendLine("                                        }");
            //sb.AppendLine("                                    }");
            //sb.AppendLine("                                });");
            sb.AppendLine("                            }");
            sb.AppendLine("                        });");
            sb.AppendLine("                    });");
            sb.AppendLine("                })");
            sb.AppendLine("                .catch(err => console.error('Failed to load content', err));");
            sb.AppendLine("        }");

            sb.AppendLine("");
            sb.AppendLine("        function nekoCancelEdit() {");
            sb.AppendLine("            modal.classList.add('hidden');");
            sb.AppendLine("        }");
            sb.AppendLine("");
            sb.AppendLine("        function nekoSaveContent() {");
            sb.AppendLine("            if (!editor) return;");
            sb.AppendLine("            const content = editor.getValue();");
            sb.AppendLine("            const path = window.nekoCurrentEditPath || window.location.pathname;");
            sb.AppendLine("            fetch('/api/neko/content', {");
            sb.AppendLine("                method: 'POST',");
            sb.AppendLine("                headers: { 'Content-Type': 'application/json' },");
            sb.AppendLine("                body: JSON.stringify({ path, content })");
            sb.AppendLine("            })");
            sb.AppendLine("            .then(res => {");
            sb.AppendLine("                if (res.ok) {");
            sb.AppendLine("                    nekoCancelEdit();");
            sb.AppendLine("                    // Notification handled by websocket reload usually, but we can do instant feedback");
            sb.AppendLine("                } else {");
            sb.AppendLine("                    alert('Failed to save');");
            sb.AppendLine("                }");
            sb.AppendLine("            })");
            sb.AppendLine("            .catch(err => alert('Failed to save: ' + err));");
            sb.AppendLine("        }");
            sb.AppendLine("");
            sb.AppendLine("        // Sidebar Drag-and-Drop Reorder (Edit Mode only)");
            sb.AppendLine("        (function() {");
            sb.AppendLine("            const sidebarRoot = document.getElementById('sidebar-list');");
            sb.AppendLine("            if (!sidebarRoot) return;");
            sb.AppendLine("            let dragEl = null;");
            sb.AppendLine("            let dragGroup = null;");
            sb.AppendLine("            let dropIndicator = null;");
            sb.AppendLine("            let dropTarget = null;");
            sb.AppendLine("            let dropBefore = true;");
            sb.AppendLine("");
            sb.AppendLine("            function ensureIndicator() {");
            sb.AppendLine("                if (!dropIndicator) {");
            sb.AppendLine("                    dropIndicator = document.createElement('div');");
            sb.AppendLine("                    dropIndicator.style.height = '2px';");
            sb.AppendLine("                    dropIndicator.style.background = '#3b82f6';");
            sb.AppendLine("                    dropIndicator.style.margin = '2px 0';");
            sb.AppendLine("                    dropIndicator.style.borderRadius = '2px';");
            sb.AppendLine("                    dropIndicator.style.pointerEvents = 'none';");
            sb.AppendLine("                    dropIndicator.id = 'neko-reorder-indicator';");
            sb.AppendLine("                }");
            sb.AppendLine("                return dropIndicator;");
            sb.AppendLine("            }");
            sb.AppendLine("");
            sb.AppendLine("            function removeIndicator() {");
            sb.AppendLine("                if (dropIndicator && dropIndicator.parentNode) {");
            sb.AppendLine("                    dropIndicator.parentNode.removeChild(dropIndicator);");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("");
            sb.AppendLine("            function cssEscape(s) {");
            sb.AppendLine("                if (window.CSS && CSS.escape) return CSS.escape(s);");
            sb.AppendLine("                return String(s).replace(/[\"\\\\]/g, '\\\\$&');");
            sb.AppendLine("            }");
            sb.AppendLine("");
            sb.AppendLine("            function siblingsInGroup(groupId) {");
            sb.AppendLine("                return Array.from(document.querySelectorAll('[data-neko-reorder=\"true\"][data-neko-parent=\"' + cssEscape(groupId) + '\"]'));");
            sb.AppendLine("            }");
            sb.AppendLine("");
            sb.AppendLine("            document.addEventListener('dragstart', (e) => {");
            sb.AppendLine("                const li = e.target.closest && e.target.closest('[data-neko-reorder=\"true\"]');");
            sb.AppendLine("                if (!li) return;");
            sb.AppendLine("                dragEl = li;");
            sb.AppendLine("                dragGroup = li.getAttribute('data-neko-parent') || '__root__';");
            sb.AppendLine("                li.style.opacity = '0.4';");
            sb.AppendLine("                try { e.dataTransfer.setData('text/plain', li.getAttribute('data-neko-path') || ''); } catch (err) {}");
            sb.AppendLine("                if (e.dataTransfer) e.dataTransfer.effectAllowed = 'move';");
            sb.AppendLine("            });");
            sb.AppendLine("");
            sb.AppendLine("            document.addEventListener('dragend', () => {");
            sb.AppendLine("                if (dragEl) dragEl.style.opacity = '';");
            sb.AppendLine("                removeIndicator();");
            sb.AppendLine("                dragEl = null;");
            sb.AppendLine("                dragGroup = null;");
            sb.AppendLine("                dropTarget = null;");
            sb.AppendLine("            });");
            sb.AppendLine("");
            sb.AppendLine("            document.addEventListener('dragover', (e) => {");
            sb.AppendLine("                if (!dragEl) return;");
            sb.AppendLine("                const over = e.target.closest && e.target.closest('[data-neko-reorder=\"true\"]');");
            sb.AppendLine("                if (!over || over === dragEl) return;");
            sb.AppendLine("                const overGroup = over.getAttribute('data-neko-parent') || '__root__';");
            sb.AppendLine("                if (overGroup !== dragGroup) return;");
            sb.AppendLine("                e.preventDefault();");
            sb.AppendLine("                if (e.dataTransfer) e.dataTransfer.dropEffect = 'move';");
            sb.AppendLine("                const rect = over.getBoundingClientRect();");
            sb.AppendLine("                const before = (e.clientY - rect.top) < (rect.height / 2);");
            sb.AppendLine("                dropTarget = over;");
            sb.AppendLine("                dropBefore = before;");
            sb.AppendLine("                const indicator = ensureIndicator();");
            sb.AppendLine("                if (before) {");
            sb.AppendLine("                    over.parentNode.insertBefore(indicator, over);");
            sb.AppendLine("                } else {");
            sb.AppendLine("                    over.parentNode.insertBefore(indicator, over.nextSibling);");
            sb.AppendLine("                }");
            sb.AppendLine("            });");
            sb.AppendLine("");
            sb.AppendLine("            document.addEventListener('drop', (e) => {");
            sb.AppendLine("                if (!dragEl || !dropTarget) { removeIndicator(); return; }");
            sb.AppendLine("                const overGroup = dropTarget.getAttribute('data-neko-parent') || '__root__';");
            sb.AppendLine("                if (overGroup !== dragGroup) { removeIndicator(); return; }");
            sb.AppendLine("                e.preventDefault();");
            sb.AppendLine("                // Section children are nested inside their <details>, so they move with the header automatically.");
            sb.AppendLine("                if (dropBefore) {");
            sb.AppendLine("                    dropTarget.parentNode.insertBefore(dragEl, dropTarget);");
            sb.AppendLine("                } else {");
            sb.AppendLine("                    dropTarget.parentNode.insertBefore(dragEl, dropTarget.nextSibling);");
            sb.AppendLine("                }");
            sb.AppendLine("                removeIndicator();");
            sb.AppendLine("                const siblings = siblingsInGroup(dragGroup);");
            sb.AppendLine("                const payload = { items: siblings.map((el, idx) => ({");
            sb.AppendLine("                    path: el.getAttribute('data-neko-path') || '',");
            sb.AppendLine("                    order: (idx + 1) * 10");
            sb.AppendLine("                })).filter(i => i.path) };");
            sb.AppendLine("                fetch('/api/neko/reorder', {");
            sb.AppendLine("                    method: 'POST',");
            sb.AppendLine("                    headers: { 'Content-Type': 'application/json' },");
            sb.AppendLine("                    body: JSON.stringify(payload)");
            sb.AppendLine("                }).then(res => {");
            sb.AppendLine("                    if (!res.ok) {");
            sb.AppendLine("                        console.error('Reorder failed', res.status);");
            sb.AppendLine("                        alert('Failed to save new order');");
            sb.AppendLine("                    }");
            sb.AppendLine("                }).catch(err => {");
            sb.AppendLine("                    console.error('Reorder request failed', err);");
            sb.AppendLine("                    alert('Failed to save new order: ' + err);");
            sb.AppendLine("                });");
            sb.AppendLine("            });");
            sb.AppendLine("");
            sb.AppendLine("            // Prevent link navigation when initiating drag on an anchor child");
            sb.AppendLine("            sidebarRoot.addEventListener('click', (e) => {");
            sb.AppendLine("                if (dragEl) { e.preventDefault(); e.stopPropagation(); }");
            sb.AppendLine("            }, true);");
            sb.AppendLine("        })();");
            sb.AppendLine("    </script>");
        }
    }
}
